### PR TITLE
add onelogin strategy

### PR DESCRIPTION
**Pull request by TrejGun**

### CODE REVIEW

**Comment by TrejGun** [comment]
@hegelstad sure thing i see error

Screen Shot 2019-11-24 at 10 56 47 PM

and probably i need value for ONELOGIN_SCOPE

**Comment by hegelstad** [comment]
Which value are you using for the callback uri: `http://localhost:3000/auth/onelogin/callback`? it needs to match exactly with the callback address set in onelogin.

ONELOGIN_SCOPE=openid profile email

**Comment by TrejGun** [comment]
yes that is what i'm using

**Comment by TrejGun** [comment]
stupid me i thought `openid profile email` should be replaced with actual email

**Comment by hegelstad** [comment]
My bad, I forgot to change the allowed callback uri from 127.0.0.1 to localhost :)

**Comment by TrejGun** [comment]
how can i create user?
trejgun@gmail.com/password

**Comment by hegelstad** [comment]
Pictures for readme:
Screenshot 2019-11-24 at 22 05 45
Screenshot 2019-11-24 at 22 02 55

I will create an account for you now with these credentials `trejgun@gmail.com/password`, thanks for your patience 💯

**Comment by hegelstad** [comment]
username: trejgun@gmail.com
otp: 66007234

**Comment by TrejGun** [comment]
it worked
thanks a lot for your contribution!

**Comment by hegelstad** [comment]
🎉🎉🎉

Also, just now I figured how to set login_hint which will prefill username in onelogin dialog if the user exists:

```typescript
@Injectable()
export class OneloginGuard extends AuthGuard('onelogin') implements CanActivate {
  options: AuthorizationParameters;

  async canActivate(context: ExecutionContext) {
    const request = context.switchToHttp().getRequest();
    if (request.query.email) this.setLoginHint(request);

    const result = (await super.canActivate(context)) as boolean;
    await super.logIn(request);
    return result;
  }

  setLoginHint(request: Request) {
    this.options = {
      login_hint: request.query.email
    }
  }
}
```

Maybe you think it is worth adding, but it adds complexity.

**Comment by hegelstad** [comment]
Thanks for adding the strategy example, to my knowledge this is the first such example online! 🥇

**Comment by TrejGun** [comment]
looks like we are pushing the limits)))

**Pull request merged**
